=== api-evangelist/zapier/json-schema/partner-api-zap-step-app-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ZapStepApp",
  "description": "Data for the App used in a given Zap's step",
  "$id": "https://raw.githubusercontent.com/api-evangelist/zapier/refs/heads/main/json-schema/partner-api-zap-step-app-schema.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "The numerical identifier of this Zap step's App",
      "example": 100
    },
    "uuid": {
      "type": "string",
      "description": "UUID identifier for this Zap step's App",
      "example": "550e8400-e29b-41d4-a716-446655440000"
    },
    "title": {
      "type": "string",
      "description": "The name of this App",
      "example": "Example Name"
    },
    "slug": {
      "type": "string",
      "description": "The shortened slug for this App",
      "example": "example-value"
    },
    "description": {
      "type": "string",
      "description": "The description of this App",
      "example": "Example description for this resource."
    },
    "hex_color": {
      "type": "string",
      "description": "The primary (hex) color for this App",
      "example": "example-value"
    },
    "image": {
      "type": "string",
      "description": "The image for this App",
      "example": "example-value"
    },
    "images": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ZapTemplateStepImages"
        }
      ],
      "description": "A set of images of various sizes for this App",
      "example": "example-value"
    },
    "api": {
      "type": "string",
      "description": "The name of the API this App references",
      "example": "example-value"
    },
    "url": {
      "type": "string",
      "format": "uri",
      "readOnly": true,
      "description": "The URL for this App",
      "example": "https://example.com/path/abc123"
    }
  },
  "required": [
    "api",
    "description",
    "hex_color",
    "id",
    "image",
    "images",
    "slug",
    "title",
    "url",
    "uuid"
  ]
}

=== api-evangelist/zapier/examples/partner-api-zap-step-app-example.json
{
  "id": 100,
  "uuid": "550e8400-e29b-41d4-a716-446655440000",
  "title": "Example Name",
  "slug": "example-value",
  "description": "Example description for this resource.",
  "hex_color": "example-value",
  "image": "example-value",
  "images": "example-value",
  "api": "example-value",
  "url": "https://example.com/path/abc123"
}
